### ISSUE TITLE
与https://github.com/spotahome/gontroller比较类似？

### ISSUE THREAD

**Issue by wgliang** [mjaow/listwatcher#1]

**Comment by mjaow** [comment]
> _No description provided._

嗯，简单的看了下，那个没有提供一个如何基于etcd进行list & watch的操作方案，同时怎么避免后续reconile的时候频繁访问数据源

这个主要是参考client-go，将etcd数据缓存，通过非k8s对象建立内存索引，并定期维护

**Comment by wgliang** [comment]
赞👍
